// 定义类型常量，默认全部大写
const INCREMENT = ' INCREMENT'
const DECREMENT = 'DECREMENT'
const IDENTITY = 'IDENTITY'
const FORGETIDENTITY = 'FORGETIDENTITY'
const SET_LANGUAGE = 'SET_LANGUAGE'
const SET_ACCOUNT = 'SET_ACCOUNT'
const SET_PORT = 'SET_PORT'
export default {
  INCREMENT,
  DECREMENT,
  IDENTITY,
  FORGETIDENTITY,
  SET_LANGUAGE,
  SET_ACCOUNT,
  SET_PORT
}
